[package]
name = "task-stream"
version = "0.3.0"
authors = ["rise0chen <rise0chen@163.com>"]
description = "a global task spawner, run in `no_std`."
documentation = "https://docs.rs/task-stream"
homepage = "https://blog.crise.cn"
repository = "https://github.com/rise0chen/task-stream.git"
readme = "./README.md"
keywords = ["task", "stream", "spawn"]
categories = ["embedded", "asynchronous"]
license-file = "LICENSE"
edition = "2018"

[dependencies]
spin = { version = "0.9" }
fixed-queue = {version = "^0.3.0"}
futures-core = "0.3.13"
async-task = { version = "4.0.3", default-features = false }
futures-intrusive = { version = "0.4.0", default-features = false }

[dev-dependencies]
async-std = {version = "1.7", features = ["unstable"]}
